### ISSUE TITLE
Make .apk files available in Releases

### ISSUE THREAD

**Issue by myNameArnav** [simondankelmann/Bluetooth-LE-Spam#10]
Currently the .apk files are in Assets/Apk/release.apk

Moving it to dedicated releases in github will make it easier to find and download on mobile.

![tmp_adeecdaf-efa8-4f14-a373-e3d99b602215.png](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/35961071/b0482e73-158b-483f-ac3e-768b6871b446)

**Comment by MegaMind-10** [comment]
True

**Comment by simondankelmann** [comment]
Please have a look here :)

https://github.com/simondankelmann/Bluetooth-LE-Spam/releases
