### ISSUE TITLE
Apple modals

### ISSUE THREAD

**Issue by talownsu** [simondankelmann/Bluetooth-LE-Spam#100]
Even after I turn off the Bluetooth spam, iPhones continue to get notifications. I even when I went home the iPhones in my house kept getting the spam. I'm not sure what's causing it

**Comment by ha2ked** [comment]
Turn it on and off again its like a back log of requests

**Comment by yolocat-dev** [comment]
Seems like the notifications queue up, and since you probably sent them more often than dismissed them, they stacked up. Nothing that could be prevented (if iPhones doesn't send a "dismissed modal" command, but highly unlikely)
