### ISSUE TITLE
It gives errors when spam Apple devices.

### ISSUE THREAD

**Issue by muhammeddis** [simondankelmann/Bluetooth-LE-Spam#108]
![Screenshot_20231114-100407_Bluetooth LE Spam](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/77438474/17e26c66-74ac-46ed-8a83-0c7456221359)
gives an error like this when I try to spam Apple devices, what should I do?

**Comment by simondankelmann** [comment]
Which Version do you use?
Please navigate to Settings and enable the Switch for legacy Advertising

**Comment by simondankelmann** [comment]
Please try again with the latest Version from the Release Section

**Comment by muhammeddis** [comment]
i tried the latest version but still say this
