### ISSUE TITLE
Doesn't work on s10 

### ISSUE THREAD

**Issue by pandre4219** [simondankelmann/Bluetooth-LE-Spam#109]
I have a s10 with android 12 and it won't work. No crash or anything just no advertising at nearby devices. I had also tried the apple advertising via the nrf connect app which also doesn't work. Is this a problem with the android version, my phone or could it be some setting or app on my phone that's preventing it to work?

**Comment by simondankelmann** [comment]
If both nrf and Bluetooth LE Spam do not work but show no errors, it may  be that your receiving devices block such popups. please try it again with the sender and receiver right next to each other distance of 1cm max

**Comment by pandre4219** [comment]
Still doesn't work
