### ISSUE TITLE
Is there a Discord?

### ISSUE THREAD

**Issue by MemeCornucopia** [simondankelmann/Bluetooth-LE-Spam#11]
A discord server for this app would be nice.

**Comment by bobeatsshit** [comment]
Maybe would be cool to also have a about so if someone makes a video they could see your name or GitHub page

**Comment by simondankelmann** [comment]
Discord was added, please see the readme :)

**Comment by yoshimo** [comment]
Shouldn't an OpenSource App focus on Matrix? ;)

**Comment by ha2ked** [comment]
> Shouldn't an OpenSource App focus on Matrix? ;)

sorry what

**Comment by yoshimo** [comment]
Matrix is an OpenSource , decentralised chat system and not as closed and proprietary as discord

**Comment by ha2ked** [comment]
ohh ok
