### ISSUE TITLE
Celular motorola

### ISSUE THREAD

**Issue by LordVeni** [simondankelmann/Bluetooth-LE-Spam#115]
Meu celular é da Motorola. Ele entra normalmente inicia aquela lista, mas quando aperto no botão do bluetooth não acontece nada, ele não envia spam nenhum para outros celulares.
Celular motorola moto G8 Power    Android 11.  API 30

**Comment by qasimkhn** [comment]
https://youtu.be/KDqY7yST7Kw?feature=shared   check this settings before try
