### ISSUE TITLE
tesla spam

### ISSUE THREAD

**Issue by xcypher78** [simondankelmann/Bluetooth-LE-Spam#117]
is possible spam tesla ?

I saw this here " https://github.com/Flipper-XFW/Xtreme-Firmware/blob/80bff5ade85c6465d8fb3069f390a2ca9083b581/applications/external/ble_spam/protocols/fastpair.c "

  // Custom debug popups
    {0xD99CA1, "Flipper Zero"},
    {0x77FF67, "Free Robux"},
    {0xAA187F, "Free VBucks"},
    {0xDCE9EA, "Rickroll"},
    {0x87B25F, "Animated Rickroll"},
    {0xF38C02, "Boykisser"},
    {0x1448C9, "BLM"},
    {0xD5AB33, "Xtreme"},
    {0x0C0B67, "Xtreme Cta"},
    {0x13B39D, "Talking Sasquach"},
    {0xAA1FE1, "ClownMaster"},
    {0x7C6CDB, "Obama"},
    {0x005EF9, "Ryanair"},
    {0xE2106F, "FBI"},
    {0xB37A62, "Tesla"},

**Comment by eprompc** [comment]
It would be good!!

**Comment by King7749** [comment]
> 我认为更多的 25 台设备添加了新的更新
> 
> https://github.com/Flipper-XFW/Xtreme-Firmware/blob/dev/applications/external/ble_spam/protocols/fastpair.c

Can you record a video to use the operation? I have a flipper zero, but I don't know where the feature you mentioned above is used,Thank you very much

**Comment by ha2ked** [comment]
Never say never (someday)

**Comment by simondankelmann** [comment]
Included those Devices in the latest Release :)

https://github.com/simondankelmann/Bluetooth-LE-Spam/releases
