### ISSUE TITLE
Pop ups not showing

### ISSUE THREAD

**Issue by Maxibauser** [simondankelmann/Bluetooth-LE-Spam#118]
Pop ups arent showing on android tries it with android 13

**Comment by qasimkhn** [comment]
https://youtu.be/KDqY7yST7Kw?feature=shared                             try this it has all the settings to be enabled before

**Comment by THEBIGMISHA** [comment]
Same thing, the video guide doesn’t help

**Comment by THEBIGMISHA** [comment]
Same thing, the video guide doesn’t help

**Comment by simondankelmann** [comment]
please try the latest version, otherwise check if there are any error messages in the log
