### ISSUE TITLE
too many advertisers error

### ISSUE THREAD

**Issue by HikaruIchijyo** [simondankelmann/Bluetooth-LE-Spam#120]
![Screenshot_20231119-190211_Bluetooth_LE_Spam](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/38470944/398e108b-a8a0-4095-8b40-6b2cf69a23f1)

Idk whether it is error or something. Can anybody tell me how to make it work

I am on latest release & on android 13

**Comment by ha2ked** [comment]
Will get back to you on it

**Comment by ha2ked** [comment]
Turn on legacy advertising slow down the advertising and make sure Bluetooth is on

**Comment by HikaruIchijyo** [comment]
Already on
Tried with max delay.
Bluetooth already on

**Comment by ha2ked** [comment]
legacy advertising?

**Comment by ha2ked** [comment]
is it on that is

**Comment by HikaruIchijyo** [comment]
> is it on that is

Yep

**Comment by ha2ked** [comment]
Odd

**Comment by simondankelmann** [comment]
Please try again with the latest Release:

https://github.com/simondankelmann/Bluetooth-LE-Spam/releases

**Comment by HikaruIchijyo** [comment]
> Please try again with the latest Release:
> 
> https://github.com/simondankelmann/Bluetooth-LE-Spam/releases

Still same

![Screenshot_20231119-232259_Bluetooth_LE_Spam.png](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/38470944/773c104a-96c7-458c-85b5-ef4bc9b71405)

**Comment by simondankelmann** [comment]
whats your interval and avertising mode now ?

**Comment by HikaruIchijyo** [comment]
> whats your interval and avertising mode now ?

10000 ms & kitchen sync.
I tried all of them

**Comment by simondankelmann** [comment]
do you have legacy mode enabled ?

also, are you connected with any other bluetooth devices ?

**Comment by HikaruIchijyo** [comment]
> do you have legacy mode enabled ?
> 
> also, are you connected with any other bluetooth devices ?

Yes.

No

**Comment by HikaruIchijyo** [comment]
Possible to get logs or something fr u?

**Comment by simondankelmann** [comment]
if you could provide those logs i can look if there is something odd. but this issue usually appears if too many processes try to advertise at once. if you turn off bluetooth and turn it back on, and then start advertising with a delay of 1000, do you immidiately get the error at the first try or does it let you send a few times and then stops ?

**Comment by HikaruIchijyo** [comment]
> if you could provide those logs i can look if there is something odd. but this issue usually appears if too many processes try to advertise at once. if you turn off bluetooth and turn it back on, and then start advertising with a delay of 1000, do you immidiately get the error at the first try or does it let you send a few times and then stops ?

Immediately

**Comment by HikaruIchijyo** [comment]
https://bin.kv2.dev/~655ae7fa5de7ed6bfdba5c45

**Comment by simondankelmann** [comment]
do you have bluetooth turned on ? thats weird...

**Comment by HikaruIchijyo** [comment]
> do you have bluetooth turned on ? thats weird... 

Yep it is

**Comment by HikaruIchijyo** [comment]
> do you have bluetooth turned on ? thats weird... 

W8 sorry but my watch is connected to phone.
Is it causing the issue.

I just remembered that it is also connected🥹

**Comment by HikaruIchijyo** [comment]
Still same.
I just unpaired it but same

**Comment by HikaruIchijyo** [comment]
Still same
No watch
No other device
Still that error

**Comment by simondankelmann** [comment]
From the Screenshot you provided it seems your device is connected with some bluetooth device. other than that i dont know what could cause the problem. maybe you have nrf connect running or something ?  i guess you have already rebooted the phone?

very strange because the app only needs one advertisement channel

**Comment by simondankelmann** [comment]
what exact phone do you use ?

**Comment by HikaruIchijyo** [comment]
> From the Screenshot you provided it seems your device is connected with some bluetooth device. other than that i dont know what could cause the problem. maybe you have nrf connect running or something ?  i guess you have already rebooted the phone?
> 
> very strange because the app only needs one advertisement channel

Yep tried multiple times

**Comment by HikaruIchijyo** [comment]
> From the Screenshot you provided it seems your device is connected with some bluetooth device. other than that i dont know what could cause the problem. maybe you have nrf connect running or something ?  i guess you have already rebooted the phone?
> 
> very strange because the app only needs one advertisement channel

Yep tried multiple times

**Comment by HikaruIchijyo** [comment]
> what exact phone do you use ?

Redmi note 10s on custom android 13.

Is there anyway to get logs?
I am rooted though so can get logs but last time i checked there was nothing

**Comment by HikaruIchijyo** [comment]
Somehow it got fixed automatically.

I am on debug rn if it happens again i wkll just reopen it
