### ISSUE TITLE
Add program to F-Droid

### ISSUE THREAD

**Issue by Frigyes06** [simondankelmann/Bluetooth-LE-Spam#136]
https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by Frigyes06** [comment]
Coolio!

**Comment by simondankelmann** [comment]
hi, it has been quite a while, but finally you can find the app on fdroid now:

https://f-droid.org/de/packages/de.simon.dankelmann.bluetoothlespam/
