### ISSUE TITLE
Make the Link in the Menu clickable 

### ISSUE THREAD

**Issue by Dtrieb** [simondankelmann/Bluetooth-LE-Spam#137]
Would be great if you could make the Link (github.com/simondankelmann) in the menu clickable.

![Screenshot_20231128-165035](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/3650284/9eb0b883-02f2-4c04-971e-af6e40ed5ffa)

**Comment by ha2ked** [comment]
thanks for the idea

**Comment by simondankelmann** [comment]
Done in the latest release thanks for your input @Dtrieb

**Comment by Dtrieb** [comment]
Now in 1.0.9. there is no link anymore.

Any possibility to add this again?
