### ISSUE TITLE
multi language

### ISSUE THREAD

**Issue by 0123-smallbottle** [simondankelmann/Bluetooth-LE-Spam#138]
Is is possible to support multi language?
Maybe using crowdin?

**Comment by ha2ked** [comment]
Nice idea but cant see it happening yet anyway

**Comment by 0123-smallbottle** [comment]
> Nice idea but cant see it happening yet anyway

This project have a strings.xml files. I think having that will let multi language support more easily?

**Comment by simondankelmann** [comment]
i noted it :) but for now this is not a high priority change
