### ISSUE TITLE
Pairing requests are very slow

### ISSUE THREAD

**Issue by Graitestboi** [simondankelmann/Bluetooth-LE-Spam#141]
It doesn't pair as fast as in the videos (for me it sends a request to any phone almost every 4-8 seconds) ive tried downloading different versions and adjusted the time to one request per second but still nothing

**Comment by Graitestboi** [comment]
Ive tried and it still doesn't work

**Comment by simondankelmann** [comment]
Closed for now, as this is something we cannot influence.
