### ISSUE TITLE
About Usage A new video please

### ISSUE THREAD

**Issue by Rehilnio** [simondankelmann/Bluetooth-LE-Spam#142]
Hello, I am using Samsung M21, I do not know how to do it because the current version is not the same as the videos on YouTube. Can you make a new user guide?
![Screenshot_20231130-185515_Bluetooth LE Spam](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/99745766/f25b4718-62c3-47bc-bb13-675eb7b2c448)

**Comment by Hitu1197** [comment]
Just click on the advertisement you want to perform (such as fast pair, continuity, kitchen sink etc.)
Turn on nearby sharing and turn off device scanning on the device you are using to perfirm the actions.

**Comment by qasimkhn** [comment]
try this guy video https://youtu.be/HtzxTts7fFA?feature=shared
