### ISSUE TITLE
app_debug VS app_release

### ISSUE THREAD

**Issue by GeorgeYT9769** [simondankelmann/Bluetooth-LE-Spam#145]
What is better to get? app_debug or app_release? Tried app_release and didn't work.

**Comment by ha2ked** [comment]
What do you mean by "didn't work"

**Comment by GeorgeYT9769** [comment]
> What do you mean by "didn't work"  

I installed app_release and it didn't work. So I am wondering if app_debug works and if it works/doesn't work for other people.

**Comment by ha2ked** [comment]
> > What do you mean by "didn't work"
> 
> I installed app_release and it didn't work. So I am wondering if app_debug works and if it works/doesn't work for other people.

There is little to no difference between them so if one didn't work then the other one wont either

**Comment by GeorgeYT9769** [comment]
> can you be more precise on what exactly did not work ? did the app not open at all, did the app work but you had no popups on target devices etc...

Popups didn't show, and I don't think it's my device's issue. nRF app where I had the setup for advertising worked. But also many people show that your app worked. Might be an issue between app and Bluetooth adapter...
