### ISSUE TITLE
Selection changes to first option on reopen

### ISSUE THREAD

**Issue by Wombosvideo** [simondankelmann/Bluetooth-LE-Spam#157]
## Description

When the app is reopened using the notification (when jamming in the background) the selected action is dismissed and the first action is used instead.

## Steps to reproduce

1. Select a category (i.e. Apple Continuity Collection)
2. Select repeat one mode
3. Select an action (i.e. AppleTV Keyboard)
4. Press the play button
5. Minimize the app
6. Reopen the app

**Comment by ha2ked** [comment]
Will look into it

**Comment by qasimkhn** [comment]
still no custom notifications??????plzzz

**Comment by ha2ked** [comment]
Not happening sorry

**Comment by simondankelmann** [comment]
Should be fixed in 1.0.7 :)
