### ISSUE TITLE
Targeted spam

### ISSUE THREAD

**Issue by jellytail** [simondankelmann/Bluetooth-LE-Spam#159]
Is there the ability to make this be able to specify 1+ Bluetooth MAC addresses and only spam those?
Bluetooth apps such as [this one](https://play.google.com/store/apps/details?id=com.pzolee.bluetoothscanner) can scan BT and list with device name.

**Comment by simondankelmann** [comment]
Sadly,  this is not possible. Advertising Packages are Broadcasted without a specific Receiver. Everyone can receive it but its not possible to target a device to receive it.
