### ISSUE TITLE
The application needs to be fixed

### ISSUE THREAD

**Issue by Darkrevengehack** [simondankelmann/Bluetooth-LE-Spam#174]
Hello, the application needs to be fixed and made compatible with Android 9 Android 10 Android 11 Android 12 and Android 13

**Comment by ha2ked** [comment]
A little more info pls

**Comment by Darkrevengehack** [comment]
> A little more info pls

My cell phone is a Motorola g60s

Android 12

**Comment by simondankelmann** [comment]
did you clear all app data before running the app ?
if you still experience any issues please provide a log

**Comment by Darkrevengehack** [comment]
> ¿borraste todos los datos de la aplicación antes de ejecutarla? Si aún tiene algún problema, proporcione un registro

How do I provide a record?
