### ISSUE TITLE
App close immediately after start

### ISSUE THREAD

**Issue by sztuk5** [simondankelmann/Bluetooth-LE-Spam#176]
App is instantly closing when trying to open after update (1.0.7 version with data previously cleared) on Samsung S22 Ultra.

**Comment by simondankelmann** [comment]
Can you provide some logs ?

**Comment by sztuk5** [comment]
> Can you provide some logs ?

How can I do that?

**Comment by simondankelmann** [comment]
Best way would be:

clone the repo
open in android studio
connect your phone via adb
run the app through android studio on your phone
check logcat monitor for error messages

**Comment by OlekAleksander** [comment]
> App is instantly closing when trying to open after update (1.0.7 version with data previously cleared) on Samsung S22 Ultra.

I had the same issue. Uninstalling and reinstalling the app worked for me.

**Comment by ha2ked** [comment]
You could also clear app data and that will fix it

**Comment by sztuk5** [comment]
@OlekAleksander @ha2ked 
I tried multiple times to clear data and reinstall or just reinstall and it didn't work. Now I tried to clear data, uninstall, install again and clear data and it worked. Thank You!
