### ISSUE TITLE
Xiaomi 12 not working

### ISSUE THREAD

**Issue by byzuzayli** [simondankelmann/Bluetooth-LE-Spam#18]
Hi I also tried this app. I also tried from the nrf connect program, but I could not send any notifications. Are my phone's specs correct this way? MIUI 14.0.6  ![Screenshot_2023-11-02-21-55-51-327_com.smrtprjcts.blecheck.jpg](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/89015538/674f82be-dfc9-4b0c-bb0b-d5648f05a3ef)

**Comment by Justxd22** [comment]
Any updates on this? I test on xiaomi redmi note 10 pro same specs as screenshot (no le audio broadcast) , app working but no effect

**Comment by simondankelmann** [comment]
Please check out this experimental version:

https://github.com/simondankelmann/Bluetooth-LE-Spam/blob/simondankelmann/experimentalAdvertising/app/debug/app-debug.apk

This needs some more testing but today i saw it working an a poco x3

**Comment by simondankelmann** [comment]
@byzuzayli 

Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

**Comment by Vitaliklidy** [comment]
> Hi I also tried this app. I also tried from the nrf connect program, but I could not send any notifications. Are my phone's specs correct this way? MIUI 14.0.6  ![Screenshot_2023-11-02-21-55-51-327_com.smrtprjcts.blecheck.jpg](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/89015538/674f82be-dfc9-4b0c-bb0b-d5648f05a3ef)
> 
> 

I also tried in nrf connect but then I turn advertising tx power was changed from -7 to -11 dBm maybe that's a case

**Comment by simondankelmann** [comment]
@byzuzayli did you succeed with any of the new releases ?

**Comment by byzuzayli** [comment]
I bought flipper zero. I continue with this
