### ISSUE TITLE
Swift pair question

### ISSUE THREAD

**Issue by Didyro0** [simondankelmann/Bluetooth-LE-Spam#186]
Howdy everyone,
 This isnt exactly an issue, but can you change the devices names( like from device 3 to anything you want ). Is this possible?
Thanks for your time.

**Comment by simondankelmann** [comment]
It is in general possible up to a certain stringlength, but at the moment this is not a built in feature. you could clone the repo, modify the swift pairing generator to your needs and run the app on your phone if you would want to do that

**Comment by simondankelmann** [comment]
Closed the Issue for now, since its not really an issue :)
