### ISSUE TITLE
iOS Action Modals and iOS 17 Crash lists have exactly the same actions

### ISSUE THREAD

**Issue by nmac101** [simondankelmann/Bluetooth-LE-Spam#187]
I don't think it's supposed to. I attached a long screenshot.

![Screenshot_2023-12-16-16-39-41-49.jpg](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/34165961/997230a9-bdb0-4dcb-ac69-2fa926144471)

**Comment by ha2ked** [comment]
See it's just a change of interval if you want to crash

**Comment by simondankelmann** [comment]
actually even the payload is modified. it is intended to use the same actions as in the other list but the payload is appended with 0x000010{3 bytes random}.

**Comment by nmac101** [comment]
> actually even the payload is modified. it is intended to use the same actions as in the other list but the payload is appended with 0x000010{3 bytes random}.

wait, didnt apple fix this? https://www.zdnet.com/article/ios-17-2-update-puts-an-end-to-flipper-zero-iphone-shenanigans/
i dont have an iphone to test this btw
