### ISSUE TITLE
Redmi note 12

### ISSUE THREAD

**Issue by bashmak007** [simondankelmann/Bluetooth-LE-Spam#193]
Последнее обновление не запускается, хоть прошлое работает нормально 
![Screenshot_2023-12-19-12-00-23-267_com miui bugreport](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/103831541/5dd02896-85a8-4452-822e-261db0ee1a49)

**Comment by simondankelmann** [comment]
please delete all app data and cache and try again

**Comment by bashmak007** [comment]
Я уже и удалял и кэш и приложения и в файловом менеджере, все равно такая же проблема. Подскажите где ещё что то можно удалить?
