### ISSUE TITLE
Toggle does nothing

### ISSUE THREAD

**Issue by MemeCornucopia** [simondankelmann/Bluetooth-LE-Spam#20]
Show device name toggle changes nothing.

https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/148788549/2e062ef0-6480-4d24-8e7f-17aa70b66304

**Comment by simondankelmann** [comment]
This is only for the receiving Device, if you run any BLE Advertise Scan on another Device you should be able to see the Name of the sending Bluetooth Device
