### ISSUE TITLE
How can I send to a specific device?

### ISSUE THREAD

**Issue by W1ndys** [simondankelmann/Bluetooth-LE-Spam#216]
The Android device is not receiving any effect.
In actual testing, I've found that the Windows device is effective, but the Android device (in mainland China) is not responding. How can this be resolved or is it possible to target a specific device for sending? Your guidance on this matter would be greatly appreciated.

**Comment by simondankelmann** [comment]
you have the be really close to the receiving android device. other than that the receiving device needs to have fastpairing popups enabled. sadly its not possible to address packets directly to any specific device
