### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by UnkownPlayerX000** [simondankelmann/Bluetooth-LE-Spam#217]
Hey Simon thank you for rolling out the new features and updating the app but I got a small issue after version 1.0.6 the app crashes when I wanna open it it doesn't even load just instantly crashes however version 1.0.6 and below is working do you have any idea what's causing the issue? I have a rooted Samsung note 10+ thank you in advance

**Comment by simondankelmann** [comment]
Please try deleting all App data and cache in your phone's app settings
