### ISSUE TITLE
App always crashing 

### ISSUE THREAD

**Issue by Weirdrandomthings** [simondankelmann/Bluetooth-LE-Spam#219]
Both version 1.0.7 and 1.0.8 always crash when I try to open them, I have a rooted pixel 7a.
Deleting the app data and cache sadly does not work.
1.0.6 just works normally only those two versions don't.

**Comment by simondankelmann** [comment]
1.0.7 and 1.0.8 need the database to be recreated. it seems some android device do not clear the data correctly. if you tried the debug version please get release version, if not: please try the debug verison. if the problem persists, please try debug version again and provide some logs so we can find out what is happening :)

**Comment by Weirdrandomthings** [comment]
Sorry but I don't know how to find the logs.

**Comment by Weirdrandomthings** [comment]
I finally got it running, I used titanium backup to delete all app data and then I deleted the app and reinstalled it, now it works👍

**Comment by simondankelmann** [comment]
Nice ! Thanks for sharing a solution!
