### ISSUE TITLE
Not working on samsung flip 4

### ISSUE THREAD

**Issue by Markiian7777** [simondankelmann/Bluetooth-LE-Spam#22]
https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/101580260/29086231-98d1-4722-abb5-627bc2d0c947

I have version 0.0.2 and when I press start Button app kicks me out and not working

**Comment by ha2ked** [comment]
Try new version and make sure all permissions are given

**Comment by simondankelmann** [comment]
Closed for now as there is no further Information
