### ISSUE TITLE
Suggestion for bluetooth spam

### ISSUE THREAD

**Issue by Krisquelquechoses** [simondankelmann/Bluetooth-LE-Spam#221]
Add packets sent to the notification bar and packets not received in red. This will allow us to see if the reception is good or bad. 
I am using it for educational purposes to learn a little more about the process of your project

**Comment by simondankelmann** [comment]
to my knowledge its not possible to find out if anyone received the package. the packages sent are advertisement data that are broadcasted to any device within range.
