### ISSUE TITLE
Working on Android 8.0 and later

### ISSUE THREAD

**Issue by Fusseldieb** [simondankelmann/Bluetooth-LE-Spam#229]
I have an S10e with Android 13 and the App **works** on (ie. spams) iOS devices **just fine**.

Reporting this because README states that it would only work properly on devices older than Android 8.0.

**Comment by Vniuo** [comment]
Why Xiaomi's not responding

**Comment by Fusseldieb** [comment]
> Why Xiaomi's not responding

What do you mean not responding?

**Comment by Vniuo** [comment]
> > Why Xiaomi's not responding
> 
> What do you mean not responding?

It's about choosing the same device as Xiaomi's Bluetooth, but when sending it out, Xiaomi's phone doesn't respond (I don't know English, so I used a translator, which may have deviated from your communication)

**Comment by simondankelmann** [comment]
"Android 8.0 (API level 26) or later does not support IOS or PC" is maybe  a bit missleading. it means the app is made for android 8 and above and you cannot install it on your Windows PC or iOs Device.

**Comment by Vniuo** [comment]
I know, my device is Xiaomi, and the Android is 14
