### ISSUE TITLE
It Starts on z Fold 3 but nothing happens

### ISSUE THREAD

**Issue by GammaPotato** [simondankelmann/Bluetooth-LE-Spam#23]
Newest app version but not working. Windows shows only on device "Unknown Device". Fast pairing didnt work on android devices.

EDIT
 Force closed the app and reset every permission. Fast pairing is working fine now

**Comment by ha2ked** [comment]
Nice pls close Issue
:)

**Comment by GammaPotato** [comment]
> Nice pls close Issue :)

Uhm. Swift is not working. "Unknown device" on newest version

**Comment by GammaPotato** [comment]
@simondankelmann 

Action "Modals' is working now on apple decives but pop didnt work. The app shows success full send but nothing happens. Holding the phones together will not help to

**Comment by simondankelmann** [comment]
Which App version did you use ? Please try again after activating the Switch in the Settings. If you already had it activated please try without it.

**Comment by simondankelmann** [comment]
Closed for now as there is no further Information
