### ISSUE TITLE
"The app is crashing on the Samsung Galaxy M52 device."

### ISSUE THREAD

**Issue by Srarrows** [simondankelmann/Bluetooth-LE-Spam#239]
"When trying to open the app, it closes by itself." 

"Version used:" 1.0.8

**Comment by simondankelmann** [comment]
please try and delete all app data and cache. it that does not help, please provide some logs

**Comment by TheAnonymousXAlt** [comment]
Use the debug version.

**Comment by simondankelmann** [comment]
did you have any success on that ?

**Comment by TheAnonymousXAlt** [comment]
Yes, the debug seems to be more stable.
