### ISSUE TITLE
android 14 problem

### ISSUE THREAD

**Issue by usernameisnotavailablue** [simondankelmann/Bluetooth-LE-Spam#242]
Hello,I recently updated my device on Android 14 with Android 13 everything was fine, the application itself works but here is a function that you can spam to others phones , in application shows that it spams but in fact it no function

**Comment by ha2ked** [comment]
Okay that is actually a nice theory but i dont know how that could affect it

**Comment by KovaliykSerhii** [comment]
I use Android 14 on Pixel 8 pro . It's work ok . I test Samsung Easy Setup .
