### ISSUE TITLE
Dosent work

### ISSUE THREAD

**Issue by Zayedbj** [simondankelmann/Bluetooth-LE-Spam#245]
I installed the app and then I tried the Bluetooth spam and it dosent work,I am currently using samsung A52 and I have an xiamoi tablet and a xiamoi phone 11 lite 5g and I tried to spam them (the Bluetooth was on) and it didn't work. Can someone help??

**Comment by Denalgus2** [comment]
It looks like most Android phones have patched this

**Comment by ha2ked** [comment]
There not much we can do sorry 😔.

**Comment by simondankelmann** [comment]
i too had the feeling that much less popups appear nowadays. maybe the google devs implemented some limitations ?!

**Comment by Zayedbj** [comment]
So I tried it again and it worked with iPhones but it dosent keep spamming it does the Pop on the iPhone like every 30 sec or so

**Comment by simondankelmann** [comment]
Is the iPhone updated to the latest iOS ? This really sounds like they limited the number of popups

**Comment by simondankelmann** [comment]
I assume you tried the action modals ?

**Comment by Zayedbj** [comment]
> Is the iPhone updated to the latest iOS ? This really sounds like they limited the number of popups

Yes it is I think they really limited the Pop ups

**Comment by Zayedbj** [comment]
> I assume you tried the action modals ?

Action modals? Wdym?

**Comment by simondankelmann** [comment]
I mean when you spammed the iPhone, did you go to the continuity page and selected the iOS action modals list ?

**Comment by Denalgus2** [comment]
The ios 17.2 update patched most of the spamming, it is no longer possible to crash the iPhones, and the popups are much more limited. For the androids I've noticed that it works really well on the older phones, while the newest ones are not affected by the spam at all

**Comment by simondankelmann** [comment]
At least this whole topic brought so much attention that it had to be fixed 😅

**Comment by prololgh1** [comment]
On my s23 ultra it works well even on 17.4 I cant crash my friends phone but I don't mind that. I also crashed a app lol on 17.4 btw he's the one that showed me this
