### ISSUE TITLE
Allow user to select which payloads to send

### ISSUE THREAD

**Issue by TailsFanLOL** [simondankelmann/Bluetooth-LE-Spam#249]
Hey! Let's say, for example, I wanna only target Microsoft, Apple, and... ..well... ...do some denial of pleasure. But I can only select either one category or all at once. I wanna be able to go "hmmm, I wanna select this, this and that". Oh and please remove all "not working help" issues so it's easier to navigate this page.
Thank you in advance.

**Comment by simondankelmann** [comment]
Hi, this is already noted for possible future features. At the moment there is no actual plan to develop it so I will close the issue for now. But it's not forgotten ;)
