### ISSUE TITLE
"Easy Setup Buds List" does not work on Galaxy A32

### ISSUE THREAD

**Issue by liolouiiii** [simondankelmann/Bluetooth-LE-Spam#251]
Spam "Easy Setup Buds List" doesn't work on Galaxy A32 seriously I even ran it with a neighboring Galaxy S10 and the result: the Galaxy S10 doesn't see any packets. Even if I turn on "Spam Detector" on the S10 it doesn't see any activity but all other BLE advertising work, maybe I'm dumb, maybe it's just that the Bluetooh module doesn't fit, either way it doesn't work.

UPD: Yes, I tried reinstalling the app, but in the end it doesn't work.

**Comment by ha2ked** [comment]
Odd but it has been semi-patched
