### ISSUE TITLE
Android fast pair doesn't work

### ISSUE THREAD

**Issue by nandor613** [simondankelmann/Bluetooth-LE-Spam#252]
I'm trying to do fast pair from a realme 8, to an S20FE, and fast pair doesn't seem to work correctly: Most options don't work at all, and the ones that do, only show up as Amazfit Powerbuds.
Tried reinstalling etc.

**Comment by simondankelmann** [comment]
Is the receiver up to date ? On the discord I've read that Samsung may have kind of fixed the popup flood

**Comment by ha2ked** [comment]
Ya it seems to be semi-patched

**Comment by simondankelmann** [comment]
so i will close this issue as there is not much we can do about it
