### ISSUE TITLE
IOS 17 Popups are really slow

### ISSUE THREAD

**Issue by drpatrikking** [simondankelmann/Bluetooth-LE-Spam#256]
Hello, i tried spamming my friend iPhones (12 Mini and 15 Pro Max), but all of the popups take around minute or 30seconds to show and in most cases it won't even show up on iphone. I tried changing the milliseconds, but its still same. I also tried spamming Samsung phone, and it was way faster. Upon closing a popup it instantly showed another one. How can i do the same thing to iPhones?

**Comment by EinJonas187** [comment]
Try to set the interval below 100ms

**Comment by Alluseri** [comment]
Same here, interval makes no difference, 1200ms is even more reliable.

**Comment by PatrikPepega** [comment]
> Try to set the interval below 100ms

Still same nothing changed.

**Comment by mmwong1984** [comment]
any solution?

**Comment by simondankelmann** [comment]
this seems to be patched by apple. popups on latest ios versions do appear limited as i understood
