### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by WinException** [simondankelmann/Bluetooth-LE-Spam#259]
I want to edit swift device names or add more but i can't find it on src

**Comment by simondankelmann** [comment]
You can find and edit them here:

https://github.com/simondankelmann/Bluetooth-LE-Spam/blob/main/app/src/main/java/de/simon/dankelmann/bluetoothlespam/AdvertisementSetGenerators/SwiftPairAdvertisementSetGenerator.kt

after that, you have to delete the apps data and cache, this ensures that the database is recreated with the items you added :)

**Comment by WinException** [comment]
i have question bcs i see option connectable what does it do?

**Comment by simondankelmann** [comment]
> i have question bcs i see option connectable what does it do?

that is something you can set in android, propably if you want to advertise a legitimate device that some other device can connect to. i didnt dive deeper into this but changing it could cause the popups to not appear

**Comment by WinException** [comment]
btw how to fix apple ads, i want to troll my friend

**Comment by KornineQ** [comment]
how to you make categories in swift?
