### ISSUE TITLE
Add proper using instructions 

### ISSUE THREAD

**Issue by justshubham07** [simondankelmann/Bluetooth-LE-Spam#26]
Update the readme.md file with proper usage instructions.

**Comment by ha2ked** [comment]
I'll give you a quick guide

1.Install apk
2.Press on the menu and select the Fast Pairing option for android or Swift Pair option for for windows
3.Press start advertising

**Comment by simondankelmann** [comment]
Closed for now, for more references please take a look at the discord server mentioned in the readme
