### ISSUE TITLE
Android 14 \ One UI 6.0 - Not work

### ISSUE THREAD

**Issue by yonka2019** [simondankelmann/Bluetooth-LE-Spam#260]
I am trying to run the app on S23 Ultra Android 14 One UI 6.0, the application have no affect on other devices

**Comment by yonka2019** [comment]
> Works perfect for me on Android 14 and OneUI 6

Which device you have?

**Comment by GammaPotato** [comment]
Galaxy s22

**Comment by ha2ked** [comment]
It worked fine when I tested it form this device so it may be the recipient device

**Comment by yonka2019** [comment]
there is no phone that receives those packets.. totally not works
