### ISSUE TITLE
A version for other OS's

### ISSUE THREAD

**Issue by TheAnonymousXII** [simondankelmann/Bluetooth-LE-Spam#262]
You should make versions for other operating systems like Windows and Linux. This would make testing more accurate and could give access to a console.

**Comment by ha2ked** [comment]
There is alternatives for those other OS's

**Comment by TheAnonymousXII** [comment]
Where may I ask?

**Comment by ha2ked** [comment]
Take AppleJuice as an example.

**Comment by TheAnonymousXII** [comment]
Could I have the link?
