### ISSUE TITLE
On Xiaomi Poco M6 doesn't work.

### ISSUE THREAD

**Issue by Ciucea** [simondankelmann/Bluetooth-LE-Spam#282]
I have android 14, Xiaomi HyperOS 1.0.3.0 and when i open the app, it s automatically crashed. Can someone help me?

![Screenshot_2024-06-13-08-54-07-978_com google android permissioncontroller](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/108764346/5f352599-b362-4816-8090-276d57bd2979)

**Comment by StingerFingersinmyass** [comment]
Grant all necessary permissions to the application. If it doesn't work, clear the data or install the debug version and grant all necessary permissions again. Closed.

**Comment by Ciucea** [comment]
> Grant all necessary permissions to the application. If it doesn't work, clear the data or install the debug version and grant all necessary permissions again. Closed.

Now it is working. Thank you!
