### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hydropulse** [simondankelmann/Bluetooth-LE-Spam#296]
I think you should add Motorola and fix it for some Samsung devices

**Comment by DoomedButton327** [comment]
Galaxy ring, new Samsung watch, maybe a way to show what Bluetooth devices around like Samsung, iPhone,android, might not be too possible but still a good idea

**Comment by ha2ked** [comment]
If you can find the codes we would happily add them but as of now we don't have them.
