### ISSUE TITLE
Immediately crash ater asking for permissions

### ISSUE THREAD

**Issue by AlexandreKueny** [simondankelmann/Bluetooth-LE-Spam#3]
I tried both apk on my Oneplus 9 pro with Android 13.
It asks for the permissions an then immediately crash. After that, the app won't start anymore.

**Comment by vanwafang** [comment]
Same problem on my Galaxy S10 Lite, One UI version 5.1

**Comment by simondankelmann** [comment]
Hi, could you run the App in Android Studio and provide the Error Message here ?

**Comment by n00b69** [comment]
Enable Bluetooth before opening the app, it works then.

**Comment by simondankelmann** [comment]
I added some null checks, it seems there was a problem when Bluetooth is turned off while you open the App. You might download the new Version and try again :) if the Error remains, it would be great if you could submit the Errormessage from Android Studio

**Comment by vanwafang** [comment]
Thank you all. It works now  :)

**Comment by AlexandreKueny** [comment]
I can confirm that the new apk is working fine for me also.
Thank you!

**Comment by Yokthailand** [comment]
App stop after start advertising on s20fe android 13
