### ISSUE TITLE
Worked on S22 Ultra - But not Everytime

### ISSUE THREAD

**Issue by muellerh123** [simondankelmann/Bluetooth-LE-Spam#30]
I tried the App and it sent 2 times a Paining request to my test device (S22). I put the time to 5 seconds but it just sent the request 2 TImes in 5 minutes. What can do to start a true flood on my test device?

**Comment by simondankelmann** [comment]
@muellerh123 

Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

**Comment by simondankelmann** [comment]
Closed for now, as it seems some vendors have a limit
