### ISSUE TITLE
Not Working on Poco X5 Pro 5G

### ISSUE THREAD

**Issue by Boss235798** [simondankelmann/Bluetooth-LE-Spam#300]
The log is provided in the picture
![LOG](https://github.com/user-attachments/assets/cb332612-616b-4aac-8de3-556861d28489)

**Comment by ha2ked** [comment]
Try the debug version. Get back to me if that didn't work

**Comment by simondankelmann** [comment]
looking at the log it seems the db of a previously installed version was not removed completely

**Comment by simondankelmann** [comment]
thanks @ha2ked , glad it works for you now!
