### ISSUE TITLE
Bug(?)

### ISSUE THREAD

**Issue by Klgor1803** [simondankelmann/Bluetooth-LE-Spam#307]
If you click the start/pause button really fast, it the spam is faster, the faster you click, the faster it goes
goes back to normal if pause using the notification

https://github.com/user-attachments/assets/90d01500-91cb-4e94-8120-1e6e199639da

**Comment by Klgor1803** [comment]
@xcypher78 settings?

**Comment by Klgor1803** [comment]
its an app called auto clicker

**Comment by ha2ked** [comment]
That's because it restarts the advertisements every time you press. See it goes to a new device every time it is pressed (due to the random mod enabled), so it looks like it's going fast but it isn't.
