### ISSUE TITLE
Add google pixel

### ISSUE THREAD

**Issue by Bloxproject** [simondankelmann/Bluetooth-LE-Spam#308]
It would be cool to hjack my own google pixel and doing experience of a range of how far to my Galaxy phone using this app and how far can it affect the giigle pixel 9 8 7 6 or any to trick the pixel phone that it has a new accessory. And I do this for my phone.

**Comment by acidvegas** [comment]
> It would be cool to hjack my own google pixel and doing experience of a range of how far to my Galaxy phone using this app and how far can it affect the giigle pixel 9 8 7 6 or any to trick the pixel phone that it has a new accessory. And I do this for my phone.

what the fuck did I just read lol.....

**Comment by unknown1soldier** [comment]
> > It would be cool to hjack my own google pixel and doing experience of a range of how far to my Galaxy phone using this app and how far can it affect the giigle pixel 9 8 7 6 or any to trick the pixel phone that it has a new accessory. And I do this for my phone.
> 
> what the fuck did I just read lol.....

agree with you 😂

**Comment by ha2ked** [comment]
@Bloxproject If you could try rephrasing this, I am having trouble understanding you.
