### ISSUE TITLE
run as root to be able to extend the range?

### ISSUE THREAD

**Issue by Cyanide-zh** [simondankelmann/Bluetooth-LE-Spam#309]
please make an option to run as root, if possible, to modify "the byte values actually transmitted in the payload", in that case we can have a much longer range, especially when facing iOS devices.

**Comment by ha2ked** [comment]
Sorry but this project is not being actively updated. Nice idea though.

**Comment by Cyanide-zh** [comment]
> Sorry but this project is not being actively updated. Nice idea though.

OK I will await the day it comes😇.
