### ISSUE TITLE
Cant use

### ISSUE THREAD

**Issue by itsBowls** [simondankelmann/Bluetooth-LE-Spam#31]
I just clicked "start advertising" and it was immediately stopped.
![Screenshot_20231103-202358](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/58801644/60dcda2f-e90c-4339-8b55-edf516bcb3c0)

**Comment by ha2ked** [comment]
Has been fixed I think that was the problem but pls try the newest apk it may work

**Comment by simondankelmann** [comment]
@itsBowls 

Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

**Comment by simondankelmann** [comment]
Closed for now as the related bug was fixed in newer version
