### ISSUE TITLE
Close range

### ISSUE THREAD

**Issue by xcypher78** [simondankelmann/Bluetooth-LE-Spam#32]
Hello, app works but only in close range is possible expand more range ?

**Comment by Kryczyk** [comment]
I think you'll need an external device or a better phone for this, but I'm not sure

**Comment by ha2ked** [comment]
It depends on the device there is no way for the software to increase the range

**Comment by Lhotze** [comment]
> It depends on the device there is no way for the software to increase the range

Even if you had root and Magisk access or made a change to the kernel? These were my thoughts on how it might be possible (without having much knowledge of the subject matter).

For example, the app with root access checks the device's own Bluetooth settings on a software basis and rewrites any parameter changes into a Magisk module.Although if the function were actually usable, I wouldn't know what influence that could have on the Bluetooth behavior of the device in general.

**Comment by simondankelmann** [comment]
It might be possible to send raw packages (tx power bit in the payload could be modified then) through the actual hci devices on a rooted phone using BusyBox or even on system level. But I am not 100% sure about that, however the goal of this app was to make it work on a non rooted phone by just clicking a button.

**Comment by ha2ked** [comment]
> It might be possible to send raw packages (tx power bit in the payload could be modified then) through the actual hci devices on a rooted phone using BusyBox or even on system level. But I am not 100% sure about that, however the goal of this app was to make it work on a non rooted phone by just clicking a button.

It may be a bit of work but maybe if you made a root version of the app it would be greatly appreciated

**Comment by Lethaldroid** [comment]
The app indeed works in very close range. I have tried it on multiple ios devices and android as well. Literally have to keep them touching each other in order to make popups appear on the other phone

**Comment by MemeCornucopia** [comment]
> > It might be possible to send raw packages (tx power bit in the payload could be modified then) through the actual hci devices on a rooted phone using BusyBox or even on system level. But I am not 100% sure about that, however the goal of this app was to make it work on a non rooted phone by just clicking a button.
> 
> It may be a bit of work but maybe if you made a root version of the app it would be greatly appreciated

I would appreciate this as well.
