### ISSUE TITLE
Unable to interact with anything but the sliders

### ISSUE THREAD

**Issue by NoobToolzz** [simondankelmann/Bluetooth-LE-Spam#37]
I'm using an Android 10 on the release build of the app but can't switch the device name toggle, click the menu button on top left or click "Start advertising".

**Comment by ha2ked** [comment]
Odd dont know what is wrong there

**Comment by simondankelmann** [comment]
Can you try to run the app in Android Studio and share if there is anything in the log ?

**Comment by GippokratOA** [comment]
Possibly because bluetooth is turned off on your device

**Comment by simondankelmann** [comment]
@NoobToolzz 

Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

**Comment by simondankelmann** [comment]
Closed for now as there is no further Information
