### ISSUE TITLE
Is it possible to create one that could crash devices? 

### ISSUE THREAD

**Issue by Ismail20081206** [simondankelmann/Bluetooth-LE-Spam#43]

**Comment by simondankelmann** [comment]
I am not sure if its possible to create such a package on Android but once i find the time, i will investigate it.

**Comment by Ismail20081206** [comment]
Thanks for the reply

**Comment by n00b69** [comment]
A friend of mine who tried it on his Xiaomi Mi 8 says his Bluetooth no longer works after he spoofed said phone. Even after a restart.

**Comment by Ismail20081206** [comment]
Ok, I'll check it out.

**Comment by Ismail20081206** [comment]
Mine is still working on S22 Ultra

**Comment by simondankelmann** [comment]
iOS crash was added in version 1.0.7 :)
