### ISSUE TITLE
Popularly nothing  

### ISSUE THREAD

**Issue by ha2ked** [simondankelmann/Bluetooth-LE-Spam#47]
Got this error with google pixel 7 pro android 13 not affecting anything but still there
![image](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/114942587/c81eddc2-2de6-481c-8765-74768690c698)

**Comment by simondankelmann** [comment]
Thanks for sharing, this is coming from Hardware check, not really needed anymore. will change that in future anyway ;)
