### ISSUE TITLE
Spam stops when phone is turnded sideways

### ISSUE THREAD

**Issue by Schnoggi** [simondankelmann/Bluetooth-LE-Spam#48]
If you start the spam and hold the phone sideways and the display turns, the spam stops and needs to be restarted.

**Comment by ha2ked** [comment]
Thanks for making this issue

**Comment by Stepzor11** [comment]
@ha2ked it stops also if you lock the screen

**Comment by ha2ked** [comment]
It is actually the design because much more errors could  arise if we let it run on lock screen or hold the phone sideways at that

**Comment by Stepzor11** [comment]
> It is actually the design because much more errors could  arise if we let it run on lock screen or hold the phone sideways at that 

Maybe I didn't get if the first comment was sarcastic 😅, but glad that you know it 😁

**Comment by ha2ked** [comment]
No you see I told him to make this on discord 👍

**Comment by simondankelmann** [comment]
feature is implemented :)
