### ISSUE TITLE
App does not work in the background

### ISSUE THREAD

**Issue by n00b69** [simondankelmann/Bluetooth-LE-Spam#5]
This is probably intentional, but it would be nice if background functionality were to be added.

**Comment by simondankelmann** [comment]
Actually you are right, thats intentional at the moment. if you comment out the lines in the fragments onPause and onResume Method i think it will continue to work in the Background. But that could cause some weird behaviour when switching the Fragments.

**Comment by bobeatsshit** [comment]
where would this be located if i wanted to enable this?

**Comment by simondankelmann** [comment]
For Fast Pairing (Android): [here](https://github.com/simondankelmann/Bluetooth-LE-Spam/blob/main/app/src/main/java/de/simon/dankelmann/bluetoothlespam/ui/fastPairing/FastPairingFragment.kt)

For Swift Pairing (Windows): [here](https://github.com/simondankelmann/Bluetooth-LE-Spam/blob/main/app/src/main/java/de/simon/dankelmann/bluetoothlespam/ui/swiftPair/SwiftPairFragment.kt)

In this Method, the advertising is stopped:

```
    override fun onPause() {
        super.onPause()
        if(_advertisementLoopService != null){
            if(_advertisementLoopService!!.advertising){
                stopAdvertising()
            }
        }
    }
```
