### ISSUE TITLE
Reduce notification sending time and add more common devices

### ISSUE THREAD

**Issue by emirtdag** [simondankelmann/Bluetooth-LE-Spam#52]
In the application, we can send notifications once a second. I think there should be an experimental setting to increase it. We should be able to send notifications faster by accepting the risks. Also, more devices need to be added.Or support should be offered for more countries. After all, there are other devices in other countries. Notifications are working, but some of them are not going away due to this problem.

**Comment by simondankelmann** [comment]
If you have Information for more Devices, please share them here or create a pull request :)

**Comment by simondankelmann** [comment]
closed as this is implemented already
