### ISSUE TITLE
Hi, I have lots of hex data for apple popups using android if you are interested or able to implement them.

### ISSUE THREAD

**Issue by GloriousGizmos** [simondankelmann/Bluetooth-LE-Spam#54]
Let me know if this would be of any use to you.

**Comment by simondankelmann** [comment]
Sure, can you maybe add them here:

https://github.com/simondankelmann/Bluetooth-LE-Spam/blob/main/app/src/main/java/de/simon/dankelmann/bluetoothlespam/AdvertisementSetGenerators/ContinuityDevicePopUpAdvertisementSetGenerator.kt

or if they are action modals here:

https://github.com/simondankelmann/Bluetooth-LE-Spam/blob/main/app/src/main/java/de/simon/dankelmann/bluetoothlespam/AdvertisementSetGenerators/ContinuityActionModalAdvertisementSetGenerator.kt

and create a pull request ?
