### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by lucAmbr0** [simondankelmann/Bluetooth-LE-Spam#55]
On my Mi 11 Lite 5G (Android 13) both the app-release.apk and app-debug.apk aren't working. Tried with Samsung A54 5G and Oppo Find X3 Lite (both Android 13) and nothing appears after several attempts

**Comment by simondankelmann** [comment]
Please check out this experimental version:

https://github.com/simondankelmann/Bluetooth-LE-Spam/blob/simondankelmann/experimentalAdvertising/app/debug/app-debug.apk

This needs some more testing but today i saw it working an a poco x3

**Comment by lucAmbr0** [comment]
Hi, this seems to work only for a few devices on my android phones. Thank
you for your help, I'll follow your future projects :D

**Comment by antonjijo** [comment]
> On my Mi 11 Lite 5G (Android 13) both the app-release.apk and app-debug.apk aren't working. Tried with Samsung A54 5G and Oppo Find X3 Lite (both Android 13) and nothing appears after several attempts

Yes I too facing this issue

**Comment by ha2ked** [comment]
We are working on this issue but i would make it much easier if you could send logs pls

**Comment by simondankelmann** [comment]
@antonjijo @lucAmbr0 

Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

**Comment by antonjijo** [comment]
> @antonjijo @lucAmbr0 
> 
> Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

No brother I tried once more with what you said, I think you must give a update for the application, it's a request brother and thankyou for replying

**Comment by lucAmbr0** [comment]
> @antonjijo @lucAmbr0 
> 
> Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

I tried without that setting on and it doesn't work, but when I turn it on it still doesn't work and every time a device is trying to advertise the log displays "ADVERTISE_FAILED_TOO_MANY_ADVERTISERS". this is with the release version

**Comment by lucAmbr0** [comment]
> @antonjijo @lucAmbr0 
> 
> Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

I just tried with the debug version and again the debug version works. Also, this time the debug version works pretty well. Still not every device appears but much more and much more often than the previous version.

**Comment by antonjijo** [comment]
> > @antonjijo @lucAmbr0 
> > 
> > Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)
> 
> I just tried with the debug version and again the debug version works. Also, this time the debug version works pretty well. Still not every device appears but much more and much more often than the previous version.

Okay I just try and issue if any problems appears

**Comment by simondankelmann** [comment]
> > @antonjijo @lucAmbr0
> > Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)
> 
> I tried without that setting on and it doesn't work, but when I turn it on it still doesn't work and every time a device is trying to advertise the log displays "ADVERTISE_FAILED_TOO_MANY_ADVERTISERS". this is with the release version

If that happens, please just restart the app

**Comment by antonjijo** [comment]
> > > @antonjijo @lucAmbr0
> > > Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)
> > 
> > I tried without that setting on and it doesn't work, but when I turn it on it still doesn't work and every time a device is trying to advertise the log displays "ADVERTISE_FAILED_TOO_MANY_ADVERTISERS". this is with the release version
> 
> If that happens, please just restart the app 

Okay brother.

**Comment by antonjijo** [comment]
> > > @antonjijo @lucAmbr0
> > > Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)
> > 
> > I tried without that setting on and it doesn't work, but when I turn it on it still doesn't work and every time a device is trying to advertise the log displays "ADVERTISE_FAILED_TOO_MANY_ADVERTISERS". this is with the release version
> 
> If that happens, please just restart the app 

Brother please answer my question; From which Android version does the popups will come ?

**Comment by antonjijo** [comment]
> @antonjijo @lucAmbr0 
> 
> Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

Brother please contact me in : antonjijo2018@outlook.com
I just sent my issue to you in a video format, contact me here at my Outlook id.

**Comment by Rennanz** [comment]
The new version 1.0.4 is also not working on my phone, Android A13 android version is 13

**Comment by antonjijo** [comment]
Not working (issue #55)
First at all I thank that you have mailed me . I have issued that if there is no device near me switched on blutooth it is showing that started advertising successfully . I have send you a screenshot , you can see my issue in that .
________________________________

**Comment by Rennanz** [comment]
Do you have an estimate of when the problem will be resolved?

**Comment by Rennanz** [comment]
Log

Em qua., 15 de nov. de 2023 21:56, J.A.ANTON JIJO ***@***.***>
escreveu:

**Comment by Rennanz** [comment]
I'm in a place with no devices, and it keeps popping up. When I place a
device close by, it still doesn't work. These are the logs.

Em qua., 15 de nov. de 2023 21:56, J.A.ANTON JIJO ***@***.***>
escreveu:

**Comment by antonjijo** [comment]
WORKING BUT BUGS :![Screenshot_20231118_053638.jpg](https://github.com/simondankelmann/Bluetooth-LE-Spam/assets/125327493/23a03c12-7ae3-4d0c-bf53-4fcb8211070b)


 It's working now for me after I had changed some settings in victm's phone , but it's slow and showing only one or two advertisement but showing successfully advertised but only 2 or 3 only pop-uped

**Comment by Rennanz** [comment]
Will you update the application on git hub?

Em sex., 17 de nov. de 2023 21:07, J.A.ANTON JIJO ***@***.***>
escreveu:

**Comment by antonjijo** [comment]
Yes I updated


________________________________

**Comment by Rennanz** [comment]
Can you send me the link to my email?

**Comment by antonjijo** [comment]
App link ?


________________________________
