### ISSUE TITLE
Please start this app on android 13 

### ISSUE THREAD

**Issue by Kryczyk** [simondankelmann/Bluetooth-LE-Spam#60]
This app not work on android 13

**Comment by ha2ked** [comment]
It normally does

**Comment by Sewo0018** [comment]
Xiaomi 11T Pro Android 13 not working

**Comment by DerGoogler** [comment]
The app is targeted to Android 14. But the support is unknown/unconfirmed.

**Comment by simondankelmann** [comment]
As this is a duplicate of:

https://github.com/simondankelmann/Bluetooth-LE-Spam/issues/29

i will close it here :)

**Comment by skjose0705** [comment]
I'm using android 13 and it works
