### ISSUE TITLE
[Suggestion] Support to use just 1 device instead of spamming random ones

### ISSUE THREAD

**Issue by PurpleVibe32** [simondankelmann/Bluetooth-LE-Spam#71]
There should be a tab that allows us to choose just 1 of the advertising. Whenever we press the button, it would show the advertising again with the one we chosed.

**Comment by PurpleVibe32** [comment]
And maybe spam of just  1 selected device.

**Comment by ItzWyaxe** [comment]
I think it would be good too, it just came to my mind, but it seems like someone beat me to it.

**Comment by bobeatsshit** [comment]
Wouldn't it also be cool to make it faster

**Comment by simondankelmann** [comment]
Possible with the latest Release :)
