### ISSUE TITLE
No pop ups on Redmi/xiamoi note 9

### ISSUE THREAD

**Issue by Timoooooooooooooooooo** [simondankelmann/Bluetooth-LE-Spam#72]
App is working on my s22 ultra but there are no notifications or pop ups on Redmi/xiamoi note 9

**Comment by ha2ked** [comment]
Its very hit or miss

**Comment by asm00009** [comment]
Im using the app on Redmi note 12 pro and its popping on my a51

**Comment by simondankelmann** [comment]
@Timoooooooooooooooooo 

Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

**Comment by simondankelmann** [comment]
Closed for now as there is no further Information
