### ISSUE TITLE
it doesn't work that far 

### ISSUE THREAD

**Issue by selenium2106** [simondankelmann/Bluetooth-LE-Spam#73]
The effectiveness of spam is not so much at a greater distance, being less than 10cm away it resulted in many advertisements, but more than that, the messages are not as frequent or practically non-existent. Sorry if there are spelling errors, I use a translator

**Comment by ha2ked** [comment]
if you got a external bluetooth adapter it would be better

**Comment by selenium2106** [comment]
You just have to connect it through OTG and that's it? Or do you have to do additional configuration?

**Comment by Justxd22** [comment]
Needs kernel support for loading modules/usb support

**Comment by simondankelmann** [comment]
Thanks for sharing the Information, currently i think there is no way to extend the range using the android sdk. therefore i will close this issue for now.
