### ISSUE TITLE
Allow us to choose what we want to spam

### ISSUE THREAD

**Issue by scooterthedev** [simondankelmann/Bluetooth-LE-Spam#75]
It should be possible to only spam a specific text from a list, or a custom message. The text could be converted to hex, and spammed to the end-user.

**Comment by simondankelmann** [comment]
This would be possible for Swift Pairing only and certainly only a limited length of Characters

**Comment by scooterthedev** [comment]
I understand the limited characters, but why only swift pairing. It should also work for Android phones.

**Comment by simondankelmann** [comment]
we can only spam devices that are registered for fastpairing in android. there are custom debug messages (some of them already included) but the receiver needs to manually allow those popping up on their system
