### ISSUE TITLE
Little UI improvment

### ISSUE THREAD

**Issue by 1Adri1** [simondankelmann/Bluetooth-LE-Spam#85]
In the settings window you should not be able to open the settings window again in the top right corner.

For example: You can open settings 10 times and you have to press the back button 10 times to go back to the main window.

**Comment by ha2ked** [comment]
Will be fixed very soon

**Comment by simondankelmann** [comment]
Closed :) fixed in the latest Release:

https://github.com/simondankelmann/Bluetooth-LE-Spam/releases
