### ISSUE TITLE
App freezes 

### ISSUE THREAD

**Issue by Nabeel-javaid** [simondankelmann/Bluetooth-LE-Spam#89]
I installed both of the versions and after trying it for 1 time when i tried to use it again the UI freeze and i wasn't able to do anything.. Tried it like 10 times and same thing happened.

**Comment by simondankelmann** [comment]
Did you also try activating the Switch in the Settings ?

**Comment by Nabeel-javaid** [comment]
> Did you also try activating the Switch in the Settings ?

As soon as I open the app. It freezes, I'm not even able to enable that switch in the setting

**Comment by simondankelmann** [comment]
Ok i understand, is there any chance you can run it in android studio and see the logs ?
what phone and android version do you use ?
maybe you can also try granting all permission manually in the app settings.

**Comment by Nabeel-javaid** [comment]
I'm using infinix mobile phone and android version 10.

Currently I'm not able to use Android studio but maybe in future i can try and yes I've given all the permissions to the app

**Comment by simondankelmann** [comment]
Please try again with the latest Release
