### ISSUE TITLE
No pop-ups appearing on target device

### ISSUE THREAD

**Issue by herobrinenana** [simondankelmann/Bluetooth-LE-Spam#9]
For some reason I can't get any popups to appear on the target device? Is there a fix or is it supposed to not let me pair them?

**Comment by n00b69** [comment]
I have not had success getting popups on my Galaxy S7 and Galaxy S10. A friend reported it not working on his S23 Ultra either.

Xiaomi phones work fine.

**Comment by 123321mario** [comment]
I can't get the app to send anything on my Pixel 7 Pro, will test more devices later today

**Comment by Justxd22** [comment]
Same here with Xiaomi device (snapdragon chipset)

**Comment by user4302** [comment]
How do you target a specific device?
I'm using the app on my android.
I tried the fast pairing as well as the swift pairing.
It just goes through devices, and I think it repeats the same devices.
None of my 2 other Android are getting spoofed
Am I doing it wrong?

**Comment by ha2ked** [comment]
It really depends on host device and recipient device

**Comment by simondankelmann** [comment]
Please try again with the latest Version, go to Settings and enable "Use Advertising with Settings". Please also try  with both devices right next to each other because the range varies from device to device. If popups appear, please close the issue :)

**Comment by herobrinenana** [comment]
I tried using your suggestion, it's still not showing any pop-ups on Google fast pair compatible android devices. I attempted using Microsoft swift pair too and it didn't work. I'll attempt using a 3rd device later to check if it's the problem.

**Comment by user4302** [comment]
I saw in an article that certain settings need to be disabled like nearby share and stuff like that.

(Apologies if you already mntioned this on the setup instructions)

But is that the case? Or should I be able to just install and run this with no issues?

**Comment by simondankelmann** [comment]
@herobrinenana did you have any success ?

**Comment by Justxd22** [comment]
@simondankelmann can confirm lastest build is working on my xiaomi device snapdragon

**Comment by simondankelmann** [comment]
Closed for now as no more Information is provided
