### ISSUE TITLE
Iphone not working on Samsung galaxy note9

### ISSUE THREAD

**Issue by kingexplsion7** [simondankelmann/Bluetooth-LE-Spam#94]
I have a samsung galaxy note 9 and i use the apple bluetooth popup and it doesn't work. The android works but the apple doesn't please help me on why and if it has to do with my bluetooth drive.

**Comment by simondankelmann** [comment]
Please try again after enabling the Switch in the Settings

**Comment by kingexplsion7** [comment]
It now shows apple tv popup but the airpods or headphone doesn't popped up. It only popped up once. Its still not working. Or it might just be the iphone is blocking the spamming.

**Comment by ha2ked** [comment]
Its very hit and miss

**Comment by ha2ked** [comment]
> It now shows apple tv popup but the airpods or headphone doesn't popped up. It only popped up once. Its still not working. Or it might just be the iphone is blocking the spamming.

I believe that to be true

**Comment by simondankelmann** [comment]
Closed for now, iOs seems to be blocking Popups after a certain amount of Advertisers

See: #Conclusion

https://www.mobile-hacker.com/2023/11/08/android-kitchen-sink-send-ble-spam-to-ios-android-and-windows-at-once-using-android-app/
